"""Build district-constituencies.json from AC→district mapping (TN LA 234 seats, 2026)."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

_DIR = Path(__file__).resolve().parent

# District column from Wikipedia / TN CEO (Feb 2026 SIR), keyed by manifest district name.
AC_TO_DISTRICT: dict[int, str] = {
    1: "Tiruvallur",
    2: "Tiruvallur",
    3: "Tiruvallur",
    4: "Tiruvallur",
    5: "Tiruvallur",
    6: "Tiruvallur",
    7: "Chennai",
    8: "Chennai",
    9: "Tiruvallur",
    10: "Chennai",
    11: "Chennai",
    12: "Chennai",
    13: "Chennai",
    14: "Chennai",
    15: "Chennai",
    16: "Chennai",
    17: "Chennai",
    18: "Chennai",
    19: "Chennai",
    20: "Chennai",
    21: "Chennai",
    22: "Chennai",
    23: "Chennai",
    24: "Chennai",
    25: "Chennai",
    26: "Chennai",
    27: "Chennai",
    28: "Kancheepuram",
    29: "Kancheepuram",
    30: "Chengalpattu",
    31: "Chengalpattu",
    32: "Chengalpattu",
    33: "Chengalpattu",
    34: "Chengalpattu",
    35: "Chengalpattu",
    36: "Kancheepuram",
    37: "Kancheepuram",
    38: "Ranipet",
    39: "Ranipet",
    40: "Vellore",
    41: "Ranipet",
    42: "Vellore",
    43: "Vellore",
    44: "Vellore",
    45: "Vellore",
    46: "Vellore",
    47: "Tirupathur",
    48: "Tirupathur",
    49: "Tirupathur",
    50: "Tirupathur",
    51: "Krishnagiri",
    52: "Krishnagiri",
    53: "Krishnagiri",
    54: "Krishnagiri",
    55: "Krishnagiri",
    56: "Krishnagiri",
    57: "Dharmapuri",
    58: "Dharmapuri",
    59: "Dharmapuri",
    60: "Dharmapuri",
    61: "Dharmapuri",
    62: "Tiruvannamalai",
    63: "Tiruvannamalai",
    64: "Tiruvannamalai",
    65: "Tiruvannamalai",
    66: "Tiruvannamalai",
    67: "Tiruvannamalai",
    68: "Tiruvannamalai",
    69: "Tiruvannamalai",
    70: "Viluppuram",
    71: "Viluppuram",
    72: "Viluppuram",
    73: "Viluppuram",
    74: "Viluppuram",
    75: "Viluppuram",
    76: "Kallakurichi",
    77: "Kallakurichi",
    78: "Kallakurichi",
    79: "Kallakurichi",
    80: "Kallakurichi",
    81: "Salem",
    82: "Salem",
    83: "Salem",
    84: "Salem",
    85: "Salem",
    86: "Salem",
    87: "Namakkal",
    88: "Salem",
    89: "Salem",
    90: "Salem",
    91: "Salem",
    92: "Namakkal",
    93: "Namakkal",
    94: "Namakkal",
    95: "Namakkal",
    96: "Namakkal",
    97: "Erode",
    98: "Erode",
    99: "Erode",
    100: "Erode",
    101: "Tiruppur",
    102: "Tiruppur",
    103: "Erode",
    104: "Erode",
    105: "Erode",
    106: "Erode",
    107: "The Nilgiris",
    108: "The Nilgiris",
    109: "The Nilgiris",
    110: "The Nilgiris",
    111: "Coimbatore",
    112: "Tiruppur",
    113: "Tiruppur",
    114: "Tiruppur",
    115: "Coimbatore",
    116: "Coimbatore",
    117: "Coimbatore",
    118: "Coimbatore",
    119: "Coimbatore",
    120: "Coimbatore",
    121: "Coimbatore",
    122: "Coimbatore",
    123: "Coimbatore",
    124: "Coimbatore",
    125: "Tiruppur",
    126: "Tiruppur",
    127: "Dindigul",
    128: "Dindigul",
    129: "Dindigul",
    130: "Dindigul",
    131: "Dindigul",
    132: "Dindigul",
    133: "Dindigul",
    134: "Karur",
    135: "Karur",
    136: "Karur",
    137: "Perambalur",
    138: "Tiruchirappalli",
    139: "Tiruchirappalli",
    140: "Tiruchirappalli",
    141: "Tiruchirappalli",
    142: "Tiruchirappalli",
    143: "Perambalur",
    144: "Tiruchirappalli",
    145: "Tiruchirappalli",
    146: "Tiruchirappalli",
    147: "Perambalur",
    148: "Ariyalur",
    149: "Ariyalur",
    150: "Ariyalur",
    151: "Cuddalore",
    152: "Cuddalore",
    153: "Cuddalore",
    154: "Cuddalore",
    155: "Cuddalore",
    156: "Cuddalore",
    157: "Cuddalore",
    158: "Cuddalore",
    159: "Cuddalore",
    160: "Mayiladuthurai",
    161: "Mayiladuthurai",
    162: "Mayiladuthurai",
    163: "Nagapattinam",
    164: "Nagapattinam",
    165: "Nagapattinam",
    166: "Tiruvarur",
    167: "Thanjavur",
    168: "Tiruvarur",
    169: "Tiruvarur",
    170: "Thanjavur",
    171: "Thanjavur",
    172: "Thanjavur",
    173: "Thanjavur",
    174: "Thanjavur",
    175: "Thanjavur",
    176: "Thanjavur",
    177: "Thanjavur",
    178: "Pudukkottai",
    179: "Pudukkottai",
    180: "Pudukkottai",
    181: "Pudukkottai",
    182: "Pudukkottai",
    183: "Ramanathapuram",
    184: "Sivaganga",
    185: "Sivaganga",
    186: "Sivaganga",
    187: "Sivaganga",
    188: "Madurai",
    189: "Madurai",
    190: "Theni",
    191: "Madurai",
    192: "Madurai",
    193: "Madurai",
    194: "Madurai",
    195: "Madurai",
    196: "Madurai",
    197: "Theni",
    198: "Theni",
    199: "Theni",
    200: "Theni",
    201: "Theni",
    202: "Virudhunagar",
    203: "Virudhunagar",
    204: "Virudhunagar",
    205: "Virudhunagar",
    206: "Virudhunagar",
    207: "Virudhunagar",
    208: "Ramanathapuram",
    209: "Ramanathapuram",
    210: "Ramanathapuram",
    211: "Ramanathapuram",
    212: "Ramanathapuram",
    213: "Thoothukudi",
    214: "Thoothukudi",
    215: "Thoothukudi",
    216: "Thoothukudi",
    217: "Thoothukudi",
    218: "Thoothukudi",
    219: "Tenkasi",
    220: "Tenkasi",
    221: "Tenkasi",
    222: "Tenkasi",
    223: "Tirunelveli",
    224: "Tirunelveli",
    225: "Tirunelveli",
    226: "Tirunelveli",
    227: "Tirunelveli",
    228: "Tirunelveli",
    229: "Kanniyakumari",
    230: "Kanniyakumari",
    231: "Kanniyakumari",
    232: "Kanniyakumari",
    233: "Kanniyakumari",
    234: "Kanniyakumari",
}


def main() -> None:
    assert len(AC_TO_DISTRICT) == 234, len(AC_TO_DISTRICT)
    counts = Counter(AC_TO_DISTRICT.values())
    manifest_path = _DIR.parent / "TN-GOV_Districts" / "manifests" / "tn_districts.json"
    manifest_names = {
        row["name"] for row in json.loads(manifest_path.read_text(encoding="utf-8"))["districts"]
    }
    missing = sorted(manifest_names - counts.keys())
    if missing:
        raise SystemExit(f"Missing constituency counts for: {missing}")
    if sum(counts.values()) != 234:
        raise SystemExit(f"Total seats != 234: {sum(counts.values())}")

    payload = {
        "source": "Tamil Nadu Legislative Assembly constituencies (234 seats)",
        "totalConstituencies": 234,
        "totalDistricts": 38,
        "byDistrict": dict(sorted(counts.items())),
    }
    out = _DIR / "district-constituencies.json"
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(counts)} districts, {sum(counts.values())} seats)")


if __name__ == "__main__":
    main()
